### ISSUE TITLE
[Question] How to resolve those errors?

### ISSUE THREAD

**Issue by maicss** [nuxt/movies#13]
![image](https://user-images.githubusercontent.com/9784767/197465920-96e515b7-f82c-45b7-88a1-2627fa18cb0d.png)

**Comment by maicss** [comment]
Seems not regonize `extends` field in `tsconfig.json`, paths alias also not work.

**Comment by antfu** [comment]
You can run `npx nuxi prepare` or try install again after pulling 8ff60b7435a1cc49f855d8de3ba587c6054f59c7
