### ISSUE TITLE
The width of the input box is not enough

### ISSUE THREAD

**Issue by sunupdong** [nuxt/movies#21]
Hello, the width of this input box is not enough, and it is not fully displayed. 
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/52030677/201508072-3c46d59a-a0cb-47ff-97f2-de2217e5afe0.png">

**Comment by ndragun92** [comment]
I have made a PR that should fix that.

PR: https://github.com/nuxt/movies/pull/23
