### ISSUE TITLE
Suggestion to add language switcher 

### ISSUE THREAD

**Issue by ali4zimi** [nuxt/movies#40]
It can already detect the browser's default language. Isn't it nice to have a locale switcher menu to change?

**Comment by antfu** [comment]
Sounds reasonable. Are you interested in sending a PR? Thanks

**Comment by ali4zimi** [comment]
I would like to, but I am not sure whether it is good in the footer or in the sidebar.

**Comment by ali4zimi** [comment]
Fixed in pull request #41
