### ISSUE TITLE
bug: flash of unstyled content

### ISSUE THREAD

**Issue by nexxeln** [nuxt/movies#5]
On visiting the website or refreshing there is a flash of unstyled content (FOUC).

https://user-images.githubusercontent.com/95541290/196614111-22dd8a42-523d-4830-a985-7546177b8f2a.mp4

**Comment by danielroe** [comment]
https://github.com/nuxt/framework/issues/8352

**Comment by antfu** [comment]
This should be fixed on the main branch. For the upstream issue please keep track on https://github.com/nuxt/framework/issues/8352
