### ISSUE TITLE
HTML Validation issues

### ISSUE THREAD

**Issue by devinschumacher** [nuxt/movies#62]
I ran the [@nuxtjs/html-validator](https://html-validator.nuxtjs.org/) on this project and there is alot of HTML errors.

**Comment by Atinux** [comment]
Feel free to open a PR @devinschumacher 💚

**Comment by devinschumacher** [comment]
> Feel free to open a PR @devinschumacher 💚

alright @Atinux i have never done an open source pull request before and am still relatively new to anything dev related in the grand scheme of things so... i fixed a small part and submitted a PR #63. let me know how i did and if you have any advice for future PRs/etc.!
