### ISSUE TITLE
i18n interpolation doesn't work when there's no word in the current language

### ISSUE THREAD

**Issue by alexchexes** [nuxt/movies#66]
Check out the screenshots:

![2024-06-27--19-17-21--275](https://github.com/nuxt/movies/assets/49966773/98ae9e1b-3622-440e-8259-f88f4374cd4b)
![2024-06-27--19-17-11--905](https://github.com/nuxt/movies/assets/49966773/cba20b57-d80c-46ac-9fe8-783cd6c3f45a)

**How to reproduce:**
1. Navigate to the officially hosted site https://movies.nuxt.space/
2. Change language to Español (for example) and try to search for TENET movie (or any other).

Looks like this happens for all words that use interpolation, that are not present in the selected language dictionary.

**Comment by alexchexes** [comment]
This is probably the expected behavior of @nuxtjs/i18n, but I guess Nuxt Movies needs a fallback in case an i18n dictionary lacks a word. Alternatively, we could update all dictionaries using generative AI, and then follow one (or both) of these options:

1. Add an automated check to ensure that all dictionaries contain same keys.
2. Add a noticeable reminder at the very beginning of each dictionary file stating that when you add a word to it, you must also add it to all other languages.

**Comment by Archetipo95** [comment]
Am I wrong or now its working?

**Comment by alexchexes** [comment]
> Am I wrong or now its working?

No, I just PR'd (https://github.com/nuxt/movies/pull/67) the missing translations, but it doesn't solve this very issue
