### ISSUE TITLE
Unexpected duplicate view-transition-name

### ISSUE THREAD

**Issue by buglavecz** [nuxt/movies#76]
If on one page hase more carousel, and the media card component load same data, then come to the console this error:

![Image](https://github.com/user-attachments/assets/2ad557b8-ec13-4af5-a4a3-71f748d7dd9a)

**Comment by chrisleviss** [comment]
It sounds like you’re encountering an error when loading the same data in multiple carousels on a single page. To troubleshoot, check if your media card component is properly managing state and props to avoid conflicts. Consider using unique identifiers for each carousel instance to prevent data overlap. Meanwhile, if you're looking for some entertainment while you work through this issue, you can unwind with anime on [HiAnime](https://hianime.ch/)!
